on: push
name: Lint Python
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: cclauss/Find-Python-syntax-errors-action@master
    env:
      SCRAPEOPS_API_KEY: ${{ secrets.SCRAPEOPS_API_KEY }}